"""migration_003

Revision ID: 9ace8622a63a
Revises: a09d89ee89d6
Create Date: 2023-10-02 09:48:55.782374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ace8622a63a'
down_revision: Union[str, None] = 'a09d89ee89d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('first_name', sa.String(length=128), nullable=False),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('youth_policy', sa.Boolean(), nullable=False),
    sa.Column('psychologist_support', sa.Boolean(), nullable=False),
    sa.Column('civic_education', sa.Boolean(), nullable=False),
    sa.Column('legal_support', sa.Boolean(), nullable=False),
    sa.Column('youth_policy_topic', sa.INTEGER(), nullable=True),
    sa.Column('psychologist_support_topic', sa.INTEGER(), nullable=True),
    sa.Column('civic_education_topic', sa.INTEGER(), nullable=True),
    sa.Column('legal_support_topic', sa.INTEGER(), nullable=True),
    sa.Column('ban', sa.Boolean(), nullable=False),
    sa.Column('active_category', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
